"""sync models

Revision ID: b5e069e86f60
Revises: 5eea9484579a
Create Date: 2026-02-26 11:09:21.117815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e069e86f60'
down_revision: Union[str, Sequence[str], None] = '5eea9484579a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.alter_column('notificacoes', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('notificacoes_cobranca_id_fkey'), 'notificacoes', type_='foreignkey')
    op.drop_constraint(op.f('notificacoes_empresa_id_fkey'), 'notificacoes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('notificacoes_empresa_id_fkey'), 'notificacoes', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(op.f('notificacoes_cobranca_id_fkey'), 'notificacoes', 'cobrancas', ['cobranca_id'], ['id'])
    op.alter_column('notificacoes', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
